name: Docker Image CI

on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fathurdanu/be-app:${{ github.ref_name }}

  setup_and_deploy:
    needs: [push_to_registry]

    name: Setup and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}

    - name: Deploy on the GKE
      run: |-
        sed 's/TAG_VERSION/${{ github.ref_name }}/g' ./kubernetes/be-deployment-template.yaml > ./kubernetes/be-deployment.yaml
        kubectl apply -f ./kubernetes/be-deployment.yaml
        kubectl apply -f ./kubernetes/be-service.yaml
        kubectl get services be-load-balancer-service
